### ISSUE TITLE
Using container images in Charts, that are available on DockerHub

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/vas-country-risk#51]
The current configuration of the Charts still points to container images build in the catenax-ng organization instead of DockerHub
See [image.name](https://github.com/eclipse-tractusx/vas-country-risk/blob/main/charts/country-risk/values.yaml#L28) for example

It also seems like neither frontend nor backend images are properly tagged on DockerHub

See:
- https://hub.docker.com/r/tractusx/vas-country-risk/tags
- https://hub.docker.com/r/tractusx/vas-country-risk-backend/tags

only `:latest` and `:main` tag present

this is blocking #46

**Comment by fabiodmota** [comment]
Fixed also on PR https://github.com/eclipse-tractusx/vas-country-risk/pull/53

for version I suggest since I didn't do any release or version recently to docker hub , once the PR are closed we can do a release v.1.2.1 for the repos. charts are all ready according with that version , only changelog does not have the release date setup

**Comment by SebastianBezold** [comment]
I already did the release for backend. Frontend will follow, as soon as the fixes are all done.
